routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layout');
});

Route::get('room/entry/{id}/{token}', 'RoomController@entry')->name('room.entry');
//Route::get('room/entry', ['as' => 'room.entry', 'uses' => 'RoomController@entry']);
Route::post('room/check-entry', ['as' => 'room.check_entry', 'uses' => 'RoomController@checkEntry']);
Route::resource('room', 'RoomController');
Route::get('player/show', 'PlayerController@show')->name('player.show')->middleware('checkCookies');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PlayerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\RoomResource;
use App\Model\Player;
use App\Model\Room;
use App\Rules\CodeGameValid;
use App\Rules\PlayerIsUnique;
use App\Services\Cookies;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class PlayerController extends Controller
{
    public function show(Request $request, Room $room, Cookies $cookies)
    {
        $player = $cookies->get($request);
        if ($player === null) {
            throw new \Exception('PLayer not found');
        }

        if ($request->ajax()) {
        } else {
            return view('player/show',
                [
                    'player' => $player
                ]);
        }
    }
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\RoomResource;
use App\Model\Player;
use App\Model\Room;
use App\Rules\CodeGameValid;
use App\Rules\PlayerIsUnique;
use App\Services\Shuffle;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class RoomController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return new RoomResource([]);
        } else {
            return view('room/index');

        }
    }

    public function create(Request $request)
    {
        if ($request->ajax()) {
            return new RoomResource([]);
        } else {
            return view('room/create',
            [
                'room' => new room(),
                'type' => $request->get('type', 'email')
            ]);
        }
    }

    public function store(Request $request)
    {
        if ($request->ajax()) {
            return new RoomResource([]);
        } else {
            $request->validate(Room::getValidation($request->get('type', 'email')));
            $room = new Room();
            $room->createRoomFromRequest($request);
            $room->save();
            return redirect()->route('room.show', ['room' => $room->id]);
        }
    }

    public function show(Request $request, Room $room)
    {
        if ($request->ajax()) {
            return new RoomResource($room);
        } else {
            $entryUrl = route('room.entry', ['id' => $room->getId(),'token' => $room->getToken()]);
            $players = Player::all()->where('room_id', $room->id)->where('status', Player::GUEST_STATUS_ACTIVE);
            $assignments  = Shuffle::mixUp($players->toArray());

            return view('room/show',
                [
                    'room' => $room,
                    'players' => $players,
                    'assignments' => $assignments,
                    'entryUrl' => $entryUrl
            ]);
        }
    }

    public function edit(Request $request)
    {
        return new RoomResource([]);
    }

    public function update(Request $request)
    {
        return new RoomResource([]);
    }

    public function destroy(Request $request)
    {
        return new RoomResource([]);
    }

    public function entry(Request $request, int $id,string $token)
    {
        if ($request->ajax()) {
            return new RoomResource([]);
        } else {


            return view('room/entry',
                [
                    'id' => $id,
                    'token' => $token,
                    'room' => new Room(),
                ]);
        }
    }

    public function checkEntry(Request $request)
    {
        $request->validate([
            'id' => 'required|integer',
            'token' => 'required|alpha_num|max:60',
            'name' => ['required','string','max:255', new PlayerIsUnique($request->get('id'))],
            'code_game' => ['required', new CodeGameValid($request->get('id'))]
        ]);

        $player = new Player();
        $player->createFromRequest($request);
        if ($request->ajax()) {
        } else {
            return redirect()->route('player.show');
        }
    }


}

resources/views/layout.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <title>@yield('title')</title>
</head>

<body>
<div id="app">
    <!-- Navigation -->
    <a class="menu-toggle rounded" href="#">
        <i class="fa fa-bars"></i>
    </a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand">
                <a class="js-scroll-trigger" href="#page-top">Start Bootstrap</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="#page-top">Home</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="sidebar-nav-item">
                <a class="js-scroll-trigger" href="#contact">Contact</a>
            </li>
        </ul>
    </nav>

@section('header')
@section('errors')
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
@show
    <!-- Header -->
        <header class="masthead d-flex">
            <div class="container text-center my-auto">
                <h1 class="mb-1">Amigo Invisible</h1>
                <h3 class="mb-5">
                    <em>Organiza to amigo invisible gratis y sin registro</em>
                </h3>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{{ route('room.create', ['type'=> 'email']) }}">Crea amigo invisible con correos</a>
                <a class="btn btn-info btn-xl js-scroll-trigger" href="{{ route('room.create', ['type'=> 'anonimous']) }}">Crea amigo invisible</a>
                <a class="btn btn-secondary btn-xl js-scroll-trigger" href="{{ route('room.create') }}">Unete a un grupo</a>
            </div>
            <div class="overlay"></div>
        </header>
    <!-- Footer -->
        <footer class="footer text-center">
            <div class="container">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#">
                            <i class="fa fa-android"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#">
                            <i class="fa fa-apple"></i>
                        </a>
                    </li>
                </ul>
                <p class="text-muted small mb-0">Copyright &copy; Your Website {{ date('Y') }}</p>
            </div>
        </footer>
    @show
</div>
</body>

</html>

resources/views/partials/form_member.blade.php
<div class="btn-group mb-4" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-outline-primary clonable" data-clone_class=".player"
            data-append_to_class=".group-players">
        <i class="fa fa-plus"></i> Anadir jugador
    </button>
</div>

<div class="group-players">
    @php
        $player = "player-". Str::random(6);
    @endphp
    <div class="form-row player {{ $player }} mt-2 mb-2">
        <div class="form-group col-md-5">
            <label for="miembro">Correo electronico</label>
            <input type="email" class="form-control" name="player[{{ $player }}][email]"
                   aria-describedby="miembroHelp" placeholder="correo electronico del jugador">
            <small id="emailHelp" class="form-text text-muted">correo electronico del participante del sorteo</small>

        </div>
        <div class="form-group col-md-5">
            <label for="miembro">Nombre</label>
            <input type="text" class="form-control" name="player[{{ $player }}][name]"
                   aria-describedby="miembroHelp" placeholder="nombre del jugador">
            <small id="emailHelp" class="form-text text-muted">Nombre del participante del sorteo</small>
        </div>
        <div class="form-group col-md-2 align-self-end text-right">
            <button type="button" class="btn btn-outline-danger removable"
                    data-removable_class=".form-row.player.{{ $player }}">
                <i class="fa fa-trash"></i> Borrar
            </button>
            <small id="emailHelp" class="form-text text-muted">Eliminar jugador</small>
        </div>
    </div>
</div>

resources/views/player/show.blade.php
@extends('layout')
@section('header')
    <!-- Header -->
    <header class="masthead d-flex">
        <div class="container my-auto white p-4">
            <h1 class="h1 mb-1 text-left ">Amigo invisible</h1>
            {{ $player->getId() }}
            {{ $player->name }}
            {{ $player->room_id }}
        </div>
    </header>
@stop

resources/views/room/create.blade.php
@extends('layout')
@section('header')
    <!-- Header -->
    <header class="masthead d-flex">
        <div class="container my-auto white p-4">
            <h1 class="h1 mb-1 text-left ">Crear Amigo invisible</h1>
            @if($errors->any())
                <div class="alert alert-danger" role="alert">
                    <ul class="m-0 p-0">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            {{ Form::model($room,[ 'route' => 'room.store'] ) }}
            {{ Form::hidden('type', $type) }}

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="name_game">Nombre</label>
                    {{ Form::text('name', null, ['class' => 'form-control', 'required' => 'required', 'id' => 'name_game','placeholder'=> 'Nombre or titulo del juego']) }}
                    <small class="form-text text-muted">Nombre or titulo del juego</small>
                </div>
                <div class="form-group col-md-6">
                    <label for="date_of_game">Fecha</label>
                    {{ Form::date('date_of_game', null, ['class' => 'form-control']) }}
                    <small class="form-text text-muted">Cuando se reparten los regalos?</small>
                </div>
            </div>


            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="miembro">Correo electronico</label>
                    {{ Form::email('email_leader', null, ['class' => 'form-control', 'required' => 'required', 'id' => 'emailLeader','placeholder'=> 'nombre del lider']) }}
                    <small id="emailHelp" class="form-text text-muted">correo de la persona que organiza el
                        sorteo</small>

                </div>
                <div class="form-group col-md-6">
                    <label for="leader">Lider del grupo</label>
                    {{ Form::text('name_leader', null, ['class' => 'form-control', 'required' => 'required', 'id' => 'nameLeader','placeholder'=> 'nombre del lider']) }}
                    <small class="form-text text-muted">Nombre de la persona que organiza el sorteo</small>
                </div>
            </div>
            <div class="form-group">
                <label for="leader">Lider participa en amigo invisible</label>
                <div>
                    <div class="form-check form-check-inline">
                        {{ Form::radio('leader_is_playing',1, true ,['class' => 'form-check-input','required' => 'required', 'id' => 'leader_is_playing_true']) }}
                        <label class="form-check-label" for="leader_is_playing_true">Si</label>
                    </div>
                    <div class="form-check form-check-inline">
                        {{ Form::radio('leader_is_playing',0, false ,['class' => 'form-check-input', 'id' => 'leader_is_playing_false']) }}
                        <label class="form-check-label" for="leader_is_playing_false">No</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="budget">Presupuesto</label>
                <div class="input-group mb-2 mr-sm-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text">No mas de...</div>
                    </div>
                    {{ Form::number('budget', null, ['required' => 'required', 'step' => '0.01', 'class' => 'form-control', 'id' => 'budget', 'placeholder' => 'presupuesto']) }}
                    <div class="input-group-append">
                        <div class="input-group-text">Euros</div>
                    </div>
                </div>
            </div>
            @include('partials.form_member')
            {{ Form::submit('Crear amigo invisible', ['class'=> 'btn btn-success']) }}

            {{ Form::close() }}
        </div>
    </header>
@stop

resources/views/room/entry.blade.php
@extends('layout')
@section('header')
    <!-- Header -->
    <header class="masthead d-flex">
        <div class="container my-auto white p-4">
            <h1 class="h1 mb-1 text-left ">Unirte a amigo invisible</h1>

            {{ Form::model($room,[ 'route' => 'room.check_entry'] ) }}
            {{ Form::hidden('id', $id) }}
            {{ Form::hidden('room_id', $id) }}
            {{ Form::hidden('token', $token) }}

            <div class="form-group">
                <label for="name_game">Nombre</label>
                {{ Form::text('name', null, ['class' => 'form-control', 'required' => 'required', 'id' => 'name','placeholder'=> 'Nombre del participante']) }}
                <small class="form-text text-muted">Tu nombre para participar en el juego y que la gente sepa quien eres</small>
                @error('name')
                <div class="text-danger alert-danger">{{ $message }}</div>
                @enderror
            </div>

            <div class="form-group">
                <label for="code_game">Codigo</label>
                {{ Form::text('code_game', null, ['class' => 'form-control', 'required' => 'required', 'id' => 'code_game','placeholder'=> 'Introduce el Codigo']) }}
                <small class="form-text text-muted">Codigo para participar en el amigo invisible, el creador del juego lo sabe</small>
                @error('code_game')
                <div class="text-danger alert-danger">{{ $message }}</div>
                @enderror
            </div>
            {{ Form::submit('Siguiente', ['class'=> 'btn btn-success']) }}

            {{ Form::close() }}
        </div>
    </header>
@stop

resources/views/room/index.blade.php
@extends('layout')
@section('header')
    <!-- Header -->
    <header class="masthead d-flex">
        <div class="container my-auto white p-4">
            <h1 class="mb-1 text-center ">Nuevo Amigo invisible</h1>
            <form method="POST" action="{{ route('room.store') }}">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="POST">
                <div class="form-group">
                    <label for="leader">Lider del grupo</label>
                    <input type="text" class="form-control" id="leader" name="leader" aria-describedby="leaderHelp"
                           placeholder="nombre del lider">
                    <small id="emailHelp" class="form-text text-muted">Persona que organiza el sorteo</small>
                </div>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-outline-primary clonable" data-clone_class=".member"
                            data-append_to_class=".group-members">
                        <i class="fa fa-plus"></i> Anadir miembro
                    </button>
                </div>
                <div class="group-members">
                    @php
                        $member = "member-". Str::random(6);
                    @endphp
                    <div class="form-group member {{ $member }}">
                        <label for="miembro">Miembro</label>
                        <div class="form-inline">
                            <input type="text" class="form-control" id="miembro" name="member[]"
                                   aria-describedby="miembroHelp" placeholder="nombre del lider">
                            <button type="button" class="btn btn-outline-danger removable"
                                    data-removable_class=".form-group.{{ $member }}">
                                <i class="fa fa-trash"></i> Borrar
                            </button>
                        </div>
                        <small id="emailHelp" class="form-text text-muted">Persona que organiza el sorteo</small>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Submit</button>

            </form>

        </div>
    </header>
@stop

resources/views/room/show.blade.php
@extends('layout')
@section('header')
    <!-- Header -->
    <header class="masthead d-flex">
        <div class="container my-auto white p-4">
            <h1 class="h1 mb-1 text-left ">Amigo invisible creado</h1>
            <h3 class="h3">la contrasena es: <i class="text-info font-weight-bold">{{ $room->code_game }}</i></h3>
            <p>Comparte el siguiente enlace con la gente que quireras que participe en el juego: </p>
            <a href="{{ $entryUrl }}">Enlace</a>
            <p>Tambien puedes compartirlo por:</p>
            <a href="">Whatsapp</a>
            <a href="">Telegram</a>
            <a href="">Facebook</a>
            <a href="">instagram</a>
            <a href="">twitter</a>
            <a href="">Correo</a>
            <div>
                <h3>PLayers</h3>
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Player</th>
                        <th scope="col">Buys to</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($assignments as $key => $assignment)
                        <tr>
                            <th scope="row">{{ ++$key }}</th>
                            <td>{{ $assignment['player']['name'] }}</td>
                            <td>{{ $assignment['buy_to']['name'] }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </header>
@stop